name: Main

on:
  schedule:
    - cron: '0 16 1 1,7 *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Make Directories
        run: |
          mkdir img
          mkdir doc
      - name: Fetch Indexes
        run: python aio_get_sat_urls.py
      - name: Fetch Information
        run: python aio_get_sat_info.py
      - name: Zip files
        run: |
          cd ../
          zip -r workspace.zip aio_webcrawler
          sudo mv workspace.zip aio_webcrawler
      - name: Upload Files
        run: |
          export BRANCHTIME=$(date +%s%3N)
          git switch --orphan files-$BRANCHTIME
          git add -f workspace.zip
          git config user.name github-actions
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Files"
          git push -f origin files-$BRANCHTIME